language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./gradlew clean build
  - ./gradlew jacocoTestReport


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

